Giorgi/DuckDB.NET

- DuckDB.NET.Data/DuckDBCommand.cs
- DuckDB.NET.Data/DuckDBDataReader.cs
- DuckDB.NET.Samples/Program.cs
so that actual DuckDb error message is returned to caller, if it exists.
Fixes #3
> Changed evaluation order of error checking

- DuckDB.NET/Utils.cs
This is a pull request to move the Utils class to the bindings project. Eventually I want to use some of these Utils in some of the bindings (e.g. ToManagedString). I have added a flag, so one is able to disable the 'free' call after the string has been copied. Mainly because calls to duckdb_column_name and duckdb_result_error returns a const char* that is cleaned up when duckdb_destroy_result is called and shouldn't be freed by duckdb_free.
> Move Utils to bindings project

- DuckDB.NET.Data/DuckDBCommand.cs
- DuckDB.NET.Data/DuckDBDataReader.cs
- DuckDB.NET.Samples/Program.cs
- DuckDB.NET/DuckDBNativeObjects.cs
- DuckDB.NET/IBindNativeMethods.cs
- DuckDB.NET/Linux/NativeMethods.Linux.cs
- DuckDB.NET/MacOS/NativeMethods.MacOS.cs
- DuckDB.NET/Windows/NativeMethods.Windows.cs
This pull request converts DuckDBResult to a class instead of a struct. This is to avoid copying DuckDBResult at some steps. This could alternatively be done by adding ref to all the methods taking a DuckDBResult.
This changes the interface for the methods that "returns" a DuckDBResult from:
```
var queryResult = new DuckDBResult();
result = DuckDBQuery(connection, "CREATE TABLE integers(foo INTEGER, bar INTEGER);", out queryResult);
```
or alternatively:
```
result = DuckDBQuery(connection, "CREATE TABLE integers(foo INTEGER, bar INTEGER);", out var queryResult);
```
to:
```
var queryResult = new DuckDBResult();
result = DuckDBQuery(connection, "CREATE TABLE integers(foo INTEGER, bar INTEGER);", queryResult);
```
This change will also enable passing `null` instead of an instance of …
> Convert DuckDBResult to class to benefit from reference semantics.

- DuckDB.NET.Samples/Program.cs
- DuckDB.NET.Test/QueryTests.cs
- DuckDB.NET/IBindNativeMethods.cs
- DuckDB.NET/Linux/NativeMethods.Linux.cs
- DuckDB.NET/MacOS/NativeMethods.MacOS.cs
- DuckDB.NET/Windows/NativeMethods.Windows.cs
Hi
I ran into issue #25 and I set it upon myself to try to fix it and here is the result. 
I've mitigated the issues by adding the new bindings recommended in the header file [duckdb.h](https://github.com/duckdb/duckdb/blob/master/src/include/duckdb.h). I've also added a comment above the deprecated fields in DuckDBResult.
I'm a little uncertain if all functionality in the ADO layer is still functioning as it was before. This could probably be tested a bit more thoroughly.
I've marked the deprecated fields in DuckDBResult as private and I removed DuckDBColumn since it isn't really used anymore (except for maybe legacy usages)?
Feedback is welcome.
> Adding new bindings to mitigate deprecation of fields in DuckDBResult when using newer DuckDB version

- DuckDB.NET.Data/DuckDBCommand.cs
- DuckDB.NET.Data/DuckDBDataReader.cs
- DuckDB.NET.Samples/Program.cs
- DuckDB.NET/DuckDBNativeObjects.cs
This PR replace use of deprecated fields in DuckDBResult to the newly added recommended bindings (see [https://github.com/duckdb/duckdb/blob/master/src/include/duckdb.h#L214](https://github.com/duckdb/duckdb/blob/master/src/include/duckdb.h#L214)).
Feedback is welcome.
> Replace deprecated fields with calls to bindings.

- DuckDB.NET.Data/ConnectionString/DuckDBConnectionStringParser.cs
- DuckDB.NET.Data/ConnectionString/IDuckDBConnectionString.cs
- DuckDB.NET.Data/DuckDBConnection.cs
- DuckDB.NET.Data/DuckDBConnectionStringBuilder.cs
- DuckDB.NET.Data/Internal/ConnectionManager.cs
- DuckDB.NET.Test/ConnectionStringTests.cs
- DuckDB.NET.Test/DuckDBConnectionTests.cs
This pull request brings a new `DuckDBConnectionStringBuilder` class that lets to format a connections string. This PR also changes connection string parsing so that we allow spaces around `=`.
Fix #42
> Parse connection string, introduce connection string builder

- DuckDB.NET.Data/DuckDBDataReader.cs
On one of my cases `SELECT 0.0` in DuckDb internally resolved to decimal which DuckDb.NET failed to recognise.
I've added a line into `GetFieldType` to add Decimal.
> Add Decimal type

- DuckDB.NET.Data/DuckDBCommand.cs
DuckDb API doca are suggesting to call `duckdb_destroy_result` after each query to  
*"de-allocate all memory allocated for that connection"*.
In `DuckDDCommand.ExecuteNonQuery` we called `DuckDBDestroyResult` only for error path,  
but we didn't destroy the result for the success path.
> Call DuckDBDestroyResult even on success

- DuckDB.NET.Data/DuckDBDataReader.cs
- DuckDB.NET.Data/DuckDBParameter.cs
- DuckDB.NET.Data/Internal/DbTypeMap.cs
- DuckDB.NET.Data/Internal/PreparedStatement.cs
- DuckDB.NET.Test/Parameters/DateTests.cs
- DuckDB.NET.Test/Parameters/TimeTests.cs
- DuckDB.NET.Test/Parameters/TimestampTests.cs
- DuckDB.NET/DuckDBDateOnly.cs
- DuckDB.NET/DuckDBNativeObjects.cs
- DuckDB.NET/DuckDBTimeOnly.cs
- DuckDB.NET/DuckDBTimestamp.cs
- DuckDB.NET/NativeMethods.cs
Hi!
This pull requests brings support for time-related columns: TIME, DATE and TIMESTAMP. For TIMESTAMP columns we use DateTime. However, because TimeOnly and DateOnly types are only available since .net 6, we use our own types that can be converted to and from DateTime. 
Fix #45
> Support for TimeOnly, DateOnly & Timestamp

- DuckDB.NET.Test/Parameters/ParameterCollectionTests.cs
We now have failing builds. The reason is that the tests with UPDATE statements and invalid parameter values are failing. Apparently, that is because DuckDB does not execute UPDATE statements on empty tables.
> Fix tests for DuckDB v5

- DuckDB.NET.Data/Extensions/ObjectExtension.cs
- DuckDB.NET.Data/Internal/DbTypeMap.cs
- DuckDB.NET.Data/Internal/PreparedStatement.cs
- DuckDB.NET.Test/Parameters/ParameterCollectionTests.cs
This PR fixes a serious bug with null value handling. We simply were not able to use null values as parameter values. 
I think we should upload a new nuget version, as this bug makes it impossible to use the binding library in some cases.
> Fix null handling

- DuckDB.NET.Test/ModuleInit.cs
- DuckDB.NET/DownloadNativeLibs.targets
- DuckDB.NET/DuckDB.NET.csproj
This PR will add the native libraries into the nuget package under the `runtimes` folder.
> Pack native libraries into DuckDB.NET

- DuckDB.NET.Data/DuckDBConnection.cs
- DuckDB.NET.Test/ManagedAppenderTests.cs
This change is to allow the passing of a schema option on the CreateAppender something supported on the native method but not with the ADO.NET Provider. See issue #94
> Support schema parameter on CreateAppender

- DuckDB.NET.Test/ModuleInit.cs
- DuckDB.NET/Bindings.csproj
I'am trying to use the awesome library on my M1 Pro Mac with arm64 but i'am getting System.DllNotFoundException: Unable to load shared library 'duckdb' or one of its dependencies. errors.
It seems that just the osx-arm64 runtime is missing.
This is my attempt to fix this problem and i hope this change is enought and the osx-universal also work on arm64.
Please feel free to correct my small attempt :-)
> Add Apple Silicon support

- DuckDB.NET.Data/DuckDBCommand.cs
- DuckDB.NET.Data/DuckDBDataReader.cs
- DuckDB.NET.Data/Internal/PreparedStatement.cs
- DuckDB.NET.Test/DuckDBDataReaderTests.cs
- DuckDB.NET/DuckDBWrapperObjects.cs
- DuckDB.NET/NativeMethods.cs
Remaining tasks before it can be merged:
> Extract statements api

- DuckDB.NET.Test/DuckDBIntervalTests.cs
- DuckDB.NET.Test/Test.csproj
- DuckDB.NET/DuckDBNativeObjects.cs
As discussed in #112 
Close #111
> Conversions between DuckDBInterval and TimeSpan

- DuckDB.NET.Data/Internal/PreparedStatement.cs
- DuckDB.NET.Test/Parameters/ParameterCollectionTests.cs
Ignore unused parameters instead of throwing an `InvalidOperationException`.
Closes #158 
Unchanged behavior: 
1. If there are less parameters than expected, then `InvalidOperationException: Invalid number of parameters` is thrown. Covered by existing `MissingParametersThrowsException` test.
2. If there are unbound parameters, then `DuckDB.NET.Data.DuckDBException : Invalid Input Error: Values were not provided for the following prepared statement parameters:` is thrown by duckdb.
> Ignore unused query parameters

- DuckDB.NET.Bindings/NativeMethods/NativeMethods.Appender.cs
- DuckDB.NET.Bindings/Utils.cs
- DuckDB.NET.Data/DuckDBConnection.cs
- DuckDB.NET.Test/ManagedAppenderTests.cs
Added support for special characters for schema and table names in `DuckDBConnection.CreateAppender`. Fixes #162
> Issue #162 fix

- Directory.Build.props
- global.json
SourceLink is included OOTB in net 8 and does not need to be explicitly referenced
> remove SourceLink and ensure sdk 8

- DuckDB.NET.Data/DuckDBConnection.cs
- DuckDB.NET.Data/DuckDBSchema.cs
- DuckDB.NET.Data/DuckDbMetaDataCollectionNames.cs
- DuckDB.NET.Test/Parameters/SchemaTests.cs
- DuckDB.NET.Test/SchemaTests.cs
This PR implements `Connection.GetSchema`.
Standard collections:
✔️ MetaDataCollections
✔️ Restrictions
✔️ ReservedWords
❌ DataSourceInformation
❌ DataTypes
Non standard common collections
✔️ Tables
✔️ Columns
✔️ ForeignKeys
✔️ Indexes
> Implement Connection.GetSchema

- DuckDB.NET.Bindings/NativeMethods/NativeMethods.Startup.cs
- DuckDB.NET.Data/Internal/ConnectionManager.cs
- DuckDB.NET.Samples/Program.cs
- DuckDB.NET.Test/AppenderTests.cs
- DuckDB.NET.Test/OpenTests.cs
- DuckDB.NET.Test/QueryTests.cs
> Make duckdb connection string support unicode path

- DuckDB.NET.Data/Internal/PreparedStatement.cs
If no succeed, Is the `PreparedStatement `  unnecessary.
> Make the prepared statement after the check succeed

- DuckDB.NET.Data/Internal/Writer/ListVectorDataWriter.cs
- DuckDB.NET.Test/AppenderTests.cs
- DuckDB.NET.Test/DuckDBManagedAppenderListTests.cs
Fixes https://github.com/Giorgi/DuckDB.NET/issues/199
Maybe a more elegant way?
Not sure the test I added fits your standards, but gives some idea of what is going on.
> Fix Proposal for Issue 199

- DuckDB.NET.Bindings/NativeMethods/NativeMethods.LogicalType.cs
- DuckDB.NET.Data/DuckDBAppenderRow.cs
- DuckDB.NET.Data/Internal/Writer/EnumVectorDataWriter.cs
- DuckDB.NET.Data/Internal/Writer/ListVectorDataWriter.cs
- DuckDB.NET.Data/Internal/Writer/VectorDataWriterBase.cs
- DuckDB.NET.Data/Internal/Writer/VectorDataWriterFactory.cs
- DuckDB.NET.Test/DuckDBManagedAppenderListTests.cs
- DuckDB.NET.Test/DuckDBManagedAppenderTests.cs
Hello,
the `DuckDBAppender` class now supports adding enum values.
I want to get some feedback from you @Giorgi, if the code is ok and if i should improve the error handling in the `EnumVectorDataWriter` class?
I can also add additional tests if needed.
Issue: https://github.com/Giorgi/DuckDB.NET/issues/209
Kind regards
Stefan
> DuckDBAppender: Add enum support

- DuckDB.NET.Bindings/Bindings.csproj
This pull request adds support for the win-arm64 architecture.
Changes made:
- Added 'win-arm64' to the RuntimeIdentifiers property in the project file
- Included win-arm64 in the DownloadNativeLibs target to download the appropriate native library
These changes will allow the library to be used on Windows ARM64 devices, expanding the compatibility of DuckDB.NET.
> Add win-arm64 support to runtime identifiers

- Directory.Build.props
- DuckDB.NET.Bindings/Bindings.csproj
- DuckDB.NET.Data/Data.csproj
can't compile repo when doing a shallow clone (`git clone --depth 1`) because of the reference to `GitVersion.MsBuild`
this is of like a temporary solution, but the reference is not needed for the project to function so it can be disabled for development.
errors:
<details>
when running `dotnet run` and `dotnet build`:
```
/home/melty/.nuget/packages/gitversion.msbuild/5.11.1/tools/GitVersion.MsBuild.targets(9,9): error MSB3073: The command "dotnet --roll-forward Major "/home/melty/.nuget/packages/gitversion.msbuild/5.11.1/tools/netcoreapp3.1/gitversion.dll" "/home/melty/Documents/DuckDB.NET/DuckDB.NET.Bindings"  -output file -outputfile obj/gitversion.json" exited with code 1. [/home/melty/Documents/DuckDB.NET/DuckDB.NET.Bindings/Bindings.csproj::TargetFramework=net8.0]
```
</details>
> Fix DuckDb.NET not compiling on shallow clone 

- DuckDB.NET.Data/DuckDBConnection.ScalarFunction.cs
- DuckDB.NET.Test/ScalarFunctionTests.cs
New overload uses callback without `IReadOnlyList<IDuckDBDataReader>`  which is not used.
This will match parameterless table function registration.
Removed old parameterless scalar function registration method.
~Added `[Obsolete]` attribute to old registration function.~
> Add overload to register parameterless scalar function

- DuckDB.NET.Bindings/DuckDBWrapperObjects.cs
- DuckDB.NET.Test/TableFunctionTests.cs
This PR fixes decimal parsing in DuckDBWrapperObjects to use CultureInfo.InvariantCulture for consistency across cultures and adds a test to verify decimal handling in table functions under a comma-decimal culture (ka-GE).
> fix culture specific decimal parsing

- DuckDB.NET.Samples/Program.cs
Thought it might be useful to have the appender example in the sample code. And yes it disposes the reader objects :-)
> added BulkDataLoad that implements the Bulk Data Loading example from the docs

- DuckDB.NET.Data/PreparedStatement/ClrToDuckDBConverter.cs
- DuckDB.NET.Data/PreparedStatement/PreparedStatement.cs
- DuckDB.NET.Test/Parameters/DateTests.cs
> Readded value converters for DbType
